name = "nextdns-manager"
main = "worker/index.ts"
compatibility_date = "2025-11-18"

[build]
command = "npx next telemetry disable && npm run build"

[assets]
directory = "./out"

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true